### ISSUE TITLE
Mac Support?

### ISSUE THREAD

**Issue by nvedire1** [SystemAnalysisDpt-CMC-MSU/ellipsoids#48]
Am I correct in understanding that this toolbox is only compatible with Windows machines? I have a Mac and wanted to confirm that I cannot use this toolbox on it.

**Comment by heartofmars** [comment]
The latest development version ET 2.2 dev works on both Windows and Linux (tested on Linux Mint). It should work on Mac according to some users (though I didn't test it by myself). However, if you use Mac, you will have install Mac versions of both mpt3 and cvx manually and put them next to Linux and Windows versions.

**Comment by nvedire1** [comment]
So I would have to manually install the toolbox? Also, I should get the developer version and not the stable 2.1 version?

**Comment by nvedire1** [comment]
@heartofmars - thank you for your suggestion. I am trying to install the toolbox on Mac and get into trouble with the following error log in MATLAB
[error_log.txt](https://github.com/SystemAnalysisDpt-CMC-MSU/ellipsoids/files/285316/error_log.txt)

**Comment by pgagarinov** [comment]
This is because you didn't do step 6 from https://github.com/SystemAnalysisDpt-CMC-MSU/ellipsoids/wiki/Toolbox-2.1-installation-for-end-users

**Comment by nvedire1** [comment]
@pgagarinov - Like heartofmars suggested, I did install the Mac versions of the CVX and MPT toolboxes in matlab and placed them in the same directory as the ET files.. am I missing something else? Please advise.
Thanks a lot for your help :)

**Comment by nvedire1** [comment]
@pgagarinov - Thank you! Since I can't just run the .bat file, does this translate into running the s_install file again?

**Comment by pgagarinov** [comment]
> Like heartofmars suggested
It was me under a different account.

You need to follow the installation instructions and run "install" function first. This will automatically download zip archive with cvx for windows and linux from 
https://github.com/SystemAnalysisDpt-CMC-MSU/ellipsoids/releases/download/2.2dev/cvx2.1_b1110_mpt3_1_2_win32_win64_glnx64.zip

and unpack it to a special location ('externals/..." ). 

Once this is done you will have to study a content of externals folder and figure out where cvx and mpt3 should be. Your mac versions should go next to windows and linux versions so that the folder structure is preserved. I guess you will have to merge cvx into externals\all while the folder structure for mpt3 is such that there is a separate folder for each architecture. When you merge cvx into externals/all/cvx please make sure to preserve changes made to cvx_version (line 343). I had to changed that to integrate cvx into ellipsoids toolbox. 

Finally, Step 6 means that you cannot expect everything to work at the first start. This is because install/javaclasspath.txt is modified at the first start and you need to restart matlab so that it is loaded.

>Since I can't just run the .bat file,
Bat file is for Windows, there are sh Files for Linux. You will have to use Sh file to create your own file for Mac. 

All in all, we do not support Mac at any level so you will have to do a bit of "figuring out" stuff on your own.

**Comment by nvedire1** [comment]
@pgagarinov  - Good to know it is you under both accounts :)
I'll try figuring it out and then ask for more help. Thank you so much for your help so far! :)

**Comment by nvedire1** [comment]
@pgagarinov - So i've merged the cvx and mpt folders and fixed line 343 in cvx_version. I think I am now stuck with adding the paths (in the error log). Can you tell me what I should be adding and where if its not too much of a problem.
[error_log.txt](https://github.com/SystemAnalysisDpt-CMC-MSU/ellipsoids/files/286676/error_log.txt)

**Comment by pgagarinov** [comment]
It is hard to say without a closer investigation. I think what you need to do is to make a correct installation on a windows or Linux or Windows machine (virtual machine prehaps) first to make sure that the problem is actually related to using Mac and not to not following the installation instructions. Once this is done you can run two versions side by side in a debug mode and see what causes the problem.

**Comment by nvedire1** [comment]
@pgagarinov - Thank you! Will do that.

**Comment by nvedire1** [comment]
@pgagarinov  - Thank you for all your help. I was able to figure it out. The toolbox is now installed :)
